name = "api-aptis"
type = "NodeJS"  

account_id = "5279a7f74a4a2579a63b720ab43cc811"  # Thay bằng Account ID của bạn
workers_dev = true  # Nếu bạn muốn deploy lên môi trường phát triển
compatibility_flags = ["nodejs_compat"]
main = "server.js"
compatibility_date = "2024-09-23"
route = "api-aptis.workers.dev"
