version: '3.8'  # Chỉ định phiên bản của Docker Compose

services:
  app:  # Tên dịch vụ, bạn có thể đặt tên bất kỳ
    container_name: ADMIN_APTIS_API
    build:
      context: ../  # Đảm bảo Docker Compose biết nơi để xây dựng image, `.` là thư mục hiện tại (với Dockerfile và các tệp nguồn)
      dockerfile: Docker/DockerFile.api.dev  # Tên file Dockerfile nếu nó không phải là 'Dockerfile' mặc định
    volumes:
      - ../src:/app/src
      - ../server.js:/app/server.js # Gắn kết thư mục `server` trong hệ thống của bạn vào container tại `/server`
    ports:
      - "3000:3000"  # Mở cổng 3000 từ container ra ngoài (tùy thuộc vào ứng dụng của bạn, có thể thay đổi cổng)
    environment:
      - NODE_ENV=dev  # Thiết lập biến môi trường nếu cần
    command: ["yarn", "start"]  # Chạy lệnh "yarn start" khi container khởi động
